spring:
  h2:
    console:
      enabled: true
  datasource:
    schema: classpath:/static/dbh2/schema.sql
    username: sa
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  thymeleaf:
    cache: false
  mail:
    host: smtp.qq.com
    username: 3195573606@qq.com
    password: xpkfvaatkersdheb
    properties: {mail.smtp.auth: true,smtp.starttls.enable: true,smtp.starttls.required: true}
    port: 587