spring:
  h2:
    console:
      enabled: true
  datasource:
    schema: classpath:/static/dbh2/schema.sql
    username: sa
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
  jpa:
    hibernate:
      ddl-auto: validate
  thymeleaf:
    cache: false